---
- name: Execute system updates and reboot
  hosts: all 
  remote_user: ilyes
  become: yes  
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      tags: [update_cache]

    - name: Upgrade packages
      apt:
        upgrade: yes
        update_cache: yes  # Update the cache again after upgrading
      tags: [upgrade_packages]

    - name: Perform distribution upgrade
      apt:
        upgrade: dist
        update_cache: yes  # Update the cache again after performing dist-upgrade
      tags: [dist_upgrade]

    - name: Disable swap
      command: swapoff --all --verbose
      tags: [disable_swap]

    - name: Set vm.max_map_count in /etc/sysctl.conf
      lineinfile:
        path: /etc/sysctl.conf
        line: 'vm.max_map_count=1048575'
        state: present
      notify: Reload sysctl

    - name: Set TCP keepalive parameters
      sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        state: present
      with_items:
        - { name: net.ipv4.tcp_keepalive_time, value: 60 }
        - { name: net.ipv4.tcp_keepalive_probes, value: 3 }
        - { name: net.ipv4.tcp_keepalive_intvl, value: 10 }
      handlers:
        - name: Reload sysctl
          command: sysctl -p
    
    - name: Install OpenJDK 8
      apt:
        name: openjdk-8-jre
        state: present

    - name: Set OpenJDK 8 as the default Java version
      command: update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java

    - name: Check installed Java versions
      command: update-alternatives --display java
      register: java_versions
      changed_when: false

    - name: Uninstall other Java versions
      apt:
        name: "{{ item }}"
        state: absent
      with_items: "{{ java_versions.stdout_lines }}"
      when: "item != 'java is /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java'"
      ignore_errors: true
